image:
  repository: 491085404741.dkr.ecr.us-east-2.amazonaws.com/my-app
  tag: latest

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: hello-world.kaydsystems.org