image:
  repository: 123456789012.dkr.ecr.us-west-2.amazonaws.com/my-app
  tag: latest

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: hello-world.example.com